// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhqejlxvpqyyfdqrfvtp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFocWVqbHh2cHF5eWZkcXJmdnRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDIyNTUsImV4cCI6MjA1OTAxODI1NX0.z4LyVzNHwQyWel6GAq4XLLqXjz9H67QgkAk4jduf8LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);